//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cautionem.Resources.Components {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bank_ca_ES {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bank_ca_ES() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Cautionem.Resources.Components.Bank.ca-ES", typeof(Bank_ca_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string banksedition {
            get {
                return ResourceManager.GetString("banksedition", resourceCulture);
            }
        }
        
        internal static string banks {
            get {
                return ResourceManager.GetString("banks", resourceCulture);
            }
        }
        
        internal static string bankname {
            get {
                return ResourceManager.GetString("bankname", resourceCulture);
            }
        }
        
        internal static string bankdescription {
            get {
                return ResourceManager.GetString("bankdescription", resourceCulture);
            }
        }
        
        internal static string bankaccount {
            get {
                return ResourceManager.GetString("bankaccount", resourceCulture);
            }
        }
    }
}
